version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: cimg/android:2022.01.1
    environment:
      GRADLE_OPTS: -Dorg.gradle.workers.max=1 -Dorg.gradle.daemon=false -Dkotlin.compiler.execution.strategy="in-process"
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - restore_cache:
          key: jars-{{ checksum "build.gradle.kts" }}
      - run:
          name: Run Build and Tests
          command: ./gradlew assembleDebug check
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.android/build-cache
          key: jars-{{ checksum "build.gradle.kts" }}
      - store_artifacts:
          path: mobile/build/outputs/apk
          destination: apk
      - store_artifacts:
          path: mobile/build/reports
          destination: reports
